Make the setting of the environment robust. It was definitely lacking before.
(Portage version: 2.2.0_alpha95/git/Linux x86_64, unsigned Manifest commit)

diff --git a/sci-mathematics/sage-baselayout/files/sage-baselayout-5.0-gentooify-startup-script.patch b/sci-mathematics/sage-baselayout/files/sage-baselayout-5.0-gentooify-startup-script.patch
--- a/sci-mathematics/sage-baselayout/files/sage-baselayout-5.0-gentooify-startup-script.patch
+++ b/sci-mathematics/sage-baselayout/files/sage-baselayout-5.0-gentooify-startup-script.patch
@@ -1,6 +1,23 @@
---- spkg/bin/sage	2012-03-24 11:30:56.000000000 +1300
-+++ spkg/bin/sage.new	2012-03-26 15:55:44.657782870 +1300
-@@ -36,10 +36,6 @@
+--- spkg/bin/sage.orig	2012-03-24 11:30:56.000000000 +1300
++++ spkg/bin/sage	2012-03-28 10:07:18.530832119 +1300
+@@ -1,5 +1,16 @@
+ #!/usr/bin/env bash
+ 
++# Because in Gentoo we start directly from the sage comand and not the script in the
++# top level tarball we have to source sage-env straight away.
++# Do NOT redirect stderr and stdout to /dev/null,
++# since sage-env might print important error messages:
++. @GENTOO_PORTAGE_EPREFIX@/etc/sage-env
++if [ $? -ne 0 ]; then
++   echo >&2 "Error setting environment variables by sourcing '$SAGE_LOCAL/../etc/sage-env';"
++   echo >&2 "possibly contact sage-on-gentoo team."
++   exit 1
++fi
++
+ usage() {
+     echo "----------------------------------------------------------------------"
+     grep -i version "$SAGE_LOCAL/bin/sage-banner"
+@@ -36,10 +47,6 @@
      echo "                           -only-optional <tag1,...,tagn>  -- only run tests"
      echo "                            including one of the #optional tags"
      echo "                           -randorder[=seed]  -- randomize order of tests"
@@ -11,7 +28,7 @@
      echo "  -v, -version        -- print the Sage version"
      exit 0
  }
-@@ -71,8 +67,6 @@
+@@ -71,8 +78,6 @@
      ####  1.......................26..................................................78
      ####  |.....................--.|...................................................|
      echo "Running the notebook:"
@@ -20,7 +37,7 @@
      echo "  -inotebook [...]    -- start the *insecure* Sage notebook"
      echo "  -n, -notebook [...] -- start the Sage notebook (options are the same"
      echo "                         as for the notebook command in Sage)"
-@@ -103,7 +97,6 @@
+@@ -103,7 +108,6 @@
      echo "  -python [...]       -- run the Python interpreter"
      echo "  -R [...]            -- run Sage's R with given arguments"
      echo "  -scons [...]        -- run Sage's scons"
@@ -28,7 +45,7 @@
      echo "  -singular [...]     -- run Sage's singular with given arguments"
      echo "  -sqlite3 [...]      -- run Sage's sqlite3 with given arguments"
      echo "  -twistd [...]       -- run Twisted server"
-@@ -111,40 +104,8 @@
+@@ -111,40 +115,8 @@
      echo
      ####  1.......................26..................................................78
      ####  |.....................--.|...................................................|
@@ -69,7 +86,7 @@
      echo "  -startuptime        -- display how long each component of Sage takes to"
      echo "                         start up"
      echo "  -t [options] <files|dir>"
-@@ -156,8 +117,6 @@
+@@ -156,8 +128,6 @@
      echo "                           -only-optional <tag1,...,tagn>  -- only run tests"
      echo "                            including one of the #optional tags"
      echo "                           -randorder[=seed]  -- randomize order of tests"
@@ -78,7 +95,7 @@
      echo "  -tp <N> [...]       -- like -t above, but tests in parallel using N threads"
      echo "                         with 0 interpreted as a sensible default"
      echo "  -testall [options]  -- test all source files, docs, and examples.  options"
-@@ -167,10 +126,6 @@
+@@ -167,10 +137,6 @@
      ####  1.......................26..................................................78
      ####  |.....................--.|...................................................|
      echo "Documentation:"
@@ -89,7 +106,7 @@
      echo "  -search_src <string> -- search through all the Sage library code for string"
      echo "  -search_doc <string> -- search through the Sage documentation for string"
      echo "  -grep <string>      -- same as -search_src"
-@@ -180,18 +135,8 @@
+@@ -180,18 +146,8 @@
      ####  1.......................26..................................................78
      ####  |.....................--.|...................................................|
      echo "Making Sage packages or distributions:"
@@ -108,7 +125,7 @@
  
      echo
      ####  1.......................26..................................................78
-@@ -220,18 +165,18 @@
+@@ -220,20 +176,11 @@
  }
  
  # Save the current directory, so we can change back after startup
@@ -119,21 +136,20 @@
  export CUR
  
 -cd "$SAGE_ROOT"
-+cd "$SAGE_LOCAL"
- 
- # Do NOT redirect stderr and stdout to /dev/null,
- # since sage-env might print important error messages:
+-
+-# Do NOT redirect stderr and stdout to /dev/null,
+-# since sage-env might print important error messages:
 -. spkg/bin/sage-env
-+. ../../etc/sage-env
- if [ $? -ne 0 ]; then
+-if [ $? -ne 0 ]; then
 -   echo >&2 "Error setting environment variables by sourcing '$SAGE_ROOT/spkg/bin/sage-env';"
 -   echo >&2 "possibly contact sage-devel (see http://groups.google.com/group/sage-devel)."
-+   echo >&2 "Error setting environment variables by sourcing '$SAGE_LOCAL/../etc/sage-env';"
-+   echo >&2 "possibly contact sage-on-gentoo team."
-    exit 1
- fi
+-   exit 1
+-fi
++cd "$SAGE_LOCAL"
  
-@@ -255,7 +200,7 @@
+ # Sage startup script passes some funny options, which are
+ # best ignored.
+@@ -255,7 +202,7 @@
  fi
  
  
@@ -142,7 +158,7 @@
  LOGOPT=""
  
  sage_setup() {
-@@ -264,14 +209,7 @@
+@@ -264,14 +211,7 @@
          cat "$SAGE_LOCAL/bin/sage-banner"
      fi
  
@@ -158,7 +174,7 @@
      IPYTHONDIR="$DOT_SAGE/ipython" && export IPYTHONDIR
      IPYTHONRC="ipythonrc" && export IPYTHONRC
      if [ ! -d "$IPYTHONDIR" ]; then
-@@ -358,13 +296,6 @@
+@@ -358,13 +298,6 @@
      exit $?
  fi
  
@@ -172,7 +188,7 @@
  if [ "$1" = '-gap' -o "$1" = '--gap' ]; then
      cd "$CUR"
      shift
-@@ -382,7 +313,7 @@
+@@ -382,7 +315,7 @@
  if [ "$1" = '-singular'  -o "$1" = '--singular' ]; then
      cd "$CUR"
      shift
@@ -181,7 +197,7 @@
      exit $?
  fi
  
-@@ -421,13 +352,6 @@
+@@ -421,13 +354,6 @@
      exit $?
  fi
  
@@ -195,7 +211,7 @@
  if [ "$1" = '-maxima'  -o "$1" = '--maxima' ]; then
      cd "$CUR"
      shift
-@@ -477,118 +401,6 @@
+@@ -477,118 +403,6 @@
      exit $?
  fi
  
@@ -314,7 +330,7 @@
  if [ "$1" = '-gdb-ipython'  -o "$1" = '--gdb-ipython' ]; then
      cd "$CUR"
      shift
-@@ -613,51 +425,10 @@
+@@ -613,51 +427,10 @@
      exit $?
  fi
  
@@ -366,7 +382,7 @@
  if [ "$1" = "-notebook"  -o "$1" = '--notebook' -o "$1" = '-n' ]; then
     cd "$CUR"
     shift
-@@ -666,15 +437,6 @@
+@@ -666,15 +439,6 @@
     exit $?
  fi
  
@@ -382,7 +398,7 @@
  if [ "$1" = "-inotebook"  -o "$1" = '--inotebook' ]; then
     cd "$CUR"
     shift
-@@ -683,18 +445,6 @@
+@@ -683,18 +447,6 @@
     exit $?
  fi
  
@@ -401,7 +417,7 @@
  if [ "$1" = '-grep' -o "$1" = "--grep" -o "$1" = "-search_src" -o "$1" = "--search_src" ]; then
     SAGE_BANNER="no"
     sage_setup
-@@ -719,82 +469,7 @@
+@@ -719,82 +471,7 @@
     exit $?
  fi
  
@@ -485,7 +501,7 @@
     if ! [  -f  "$DOT_SAGE"/init.sage ]; then
        echo >&2 "init.sage does not exist ... creating"
        touch "$DOT_SAGE"/init.sage
-@@ -805,10 +480,7 @@
+@@ -805,10 +482,7 @@
     exit $?
  fi
  
@@ -497,7 +513,7 @@
     if ! [  -f  "$DOT_SAGE"/init.sage ]; then
        echo >&2 "init.sage does not exist ... creating"
        touch "$DOT_SAGE"/init.sage
-@@ -819,16 +491,6 @@
+@@ -819,16 +493,6 @@
     exit $?
  fi
  
@@ -514,7 +530,7 @@
  if [ "$1" = '-testall' -o "$1" = "--testall" ]; then
     shift
     sage-maketest "$@"
-@@ -845,70 +507,11 @@
+@@ -845,70 +509,11 @@
     exit $?
  fi
  
@@ -586,7 +602,7 @@
  fi
  
  if [ "$1" = '-pkg' -o "$1" = '-spkg' -o "$1" = "--pkg" -o "$1" = "--spkg" ]; then
-@@ -939,99 +542,6 @@
+@@ -939,99 +544,6 @@
     exit $?
  fi
  
@@ -686,7 +702,7 @@
  if [ "$1" = '-gdb' -o "$1" = "--gdb" ]; then
      sage_setup
      sage-gdb
-@@ -1093,10 +603,6 @@
+@@ -1093,10 +605,6 @@
  
  if [ $# -ge 1 ]; then
     T=`echo "$1" | sed -e "s/.*\.//"`
